### ISSUE TITLE
Default values for trait parameters

### ISSUE THREAD

**Issue by cfineman** [raml-org/raml-website#108]
Summary: It would be helpful to have default values for traits that could be overridden by the leveraging raml. If doing something like this (which is quite similar to the overlay concept in my eyes), perhaps the Bourne Shell syntax for defaults in variable expansion could be used (```${var:-defaultValue}```)

For example... a "pageable" trait might have a default page size

```
traits:
    pageable:
        queryParameters:
            offset:
            type: integer
            required: false
            default: 0
        limit:
            type: integer
            required: false
            default: 10

/songs
    type:
        collection:
            ...
    get:
        is: [ pageable ]
        queryParameters:
            limit:
                default: 100

/artists
    type:
        collection:
            ...
    get:
        is: [ pageable ]
```
